### ISSUE TITLE
Errorhandling

### ISSUE THREAD

**Issue by MoritzMennenga** [ISAAKiel/profileAAR#4]
Errors to handle:
 
- calculating the resiuals of the regressions to get the min max and mean values for the profile as a factor for the accuracy

**Comment by kschmuetz** [comment]
Errors taken care of:
- view column -> only N,E,S,W
- in all points of one profile number, the view has to be the same
- check if coordinates system is projected (moritz)
- Added Icon to the GUI

**Comment by MoritzMennenga** [comment]
- z-values are checked for real/float
- Indexing problems with the selected Layer (e.g. when rasters are present (above ) in the layerstructure the layer_field function fails to set the proper index of the active layer)

**Comment by kschmuetz** [comment]
Due to the addition of the QgsMapLayerComboBox there is an error that occurs if the gui is changed. The error message is something like: Can´t import qgsmaplayercombobox.h.
To get it running again go to the *.ui-file and look for:
   \<class\>QgsMapLayerComboBox\<\/class\>
   \<extends\>QComboBox\<\/extends\>
   \<header\>qgsmaplayercombobox.h\<\/header\>
Change "qgsmaplayercombobox.h" in the last line to "qgis.gui" and save the file. 
That should fix that problem.

**Comment by MoritzMennenga** [comment]
automaticly load the created shapefile as a layer in the existing qgis project --> is done

**Comment by MoritzMennenga** [comment]
A comparable number for measuaring the accuracy is now found:
After the rotation of the profile we draw a virtual line parralel to the x-axis throught the profile.
The absolute distance of each point to the line is calculated 
(Easy to do this: check_result.append(fabs(coord_trans[i][1]- ymean)) )
the min max and mean value give an idea, how good the rotation worked. On a perfect profile the values are all 0 // on a really bad profile (in theory) the values are all hight // is one point bad, the min is near 0, mean is near 0 max is the offset of the point in cm.

**Comment by MoritzMennenga** [comment]
There is a value in the export, that indicates the accuracy by giving the distance from the regression line to each point (orthogonal). As higher the number is (> 0.09 very unaccurate) as unstraight the profile is.
